// This file is generated by Slice Machine. Update with care!

import 2004 from './2004';
import 9998 from './9998';

export {
	2004,
	9998,
};

export const components = {
	2004: 2004,
	9998: 9998,
};
